const projects = [
    {
      "index": 1,
      "name": "Video Streaming Website",
      "imgsrc": "../projects/Video-Vault.png",
      "descr": " A convenient and comprehensive platform that helps users to stream any kind of video and user can save their video on this website",
      "github":"https://github.com/snehasishdasz/Video-Vault",
      "tech1": "#html ",
      "tech2": "#css",
      "tech3": "#javascript", 
    },
    {
      "index": 2,
      "name": "Weather Application",
      "imgsrc": "../projects/मौसम-Weather.png",
      "descr": "A dynamic and interactive weather application that show different locations weather. ", 
      "github":"https://github.com/snehasishdasz/mausam-weather-app",
      "tech1": "#nextjs",
      "tech2": "#scss",
      "tech3": "#firebase",
    },
    {
      "index": 3,
      "name": "Flight Portal System",
      "imgsrc": "../projects/Amigo.png",
      "descr": "An online platform where user can see the flight timing and book their flight .", 
      "github":"https://github.com/snehasishdasz/flight-portal-system",
      "tech1": "#reactjs",
      "tech2": "#css",
      "tech3": "#restapi",
    },
  ]
  
  
  const allprojects = [
    {
      index: 1,
      name: "Hospital Finder Website",
      imgsrc: "/projects/hospital-one.png",
      descr: " A convenient and comprehensive platform that helps users find nearby hospitals, providing essential info for healthcare accessibility and convenience.",
      github:"https://github.com/abhishekdasz/HospitalOne",
      techs: ["#html", "#css", "#javascript"],
    },
    {
      index: 2,
      name: "Realtime Chat Application",
      imgsrc: "/projects/chatapplication.png",
      descr: "A dynamic and interactive chat application enabling users to communicate in real-time, providing a seamless and engaging conversations. ", 
      github: "https://github.com/abhishekdasz/Realtime-Chat-Application",
      techs: ["#nextjs", "#css", "#firebase"],
    },
    {
      index: 3,
      name: "E-commerce Application",
      imgsrc: "/projects/e-commerce.png",
      descr: "An online platform offering a seamless shopping experience, showcasing products, facilitating secure transactions, and ensuring customer satisfaction.", 
      github:"https://github.com/abhishekdasz/e-commerce",
      techs: ["#reactjs", "#css","restapi"],
    },
    {
      index: 4,
      name: "Parallax Portfolio",
      imgsrc: "/projects/parallax-portfolio.png",
      descr: "An online platform offering a seamless shopping experience, showcasing products, facilitating secure transactions, and ensuring customer satisfaction.", 
      github:"https://github.com/abhishekdasz/e-commerce",
      techs: ["#html", "#css", "#javascript"],
    },
    {
      index: 5,
      name: "CineQuest",
      imgsrc: "/projects/movies-search.png",
      descr: "Access a vast collection of movies from various genres, including action, comedy, drama, thriller, and more. Explore a diverse range of films.", 
      github:"https://github.com/abhishekdasz/CineQuest",
      techs: ["#nextjs", "#rest-api", "mongodb"],
    },
    {
      index: 6,
      name: "HackSpot",
      imgsrc: "/projects/hackathon-search.png",
      descr: "Discover and register for top national, global, and state-level hackathons. Get summaries and join the coding revolution all in one platform.", 
      github: "https://github.com/abhishekdasz/e-commerce",
      techs: ["#html", "css"],
    },
    {
      index: 7,
      name: "Google Keep Clone",
      imgsrc: "/projects/google-keep.png",
      descr: "A clone app inspired by Google Keep for seamless note-taking, organization, and synchronization. Boost your productivity with this powerful tool.", 
      github: "https://github.com/abhishekdasz/e-commerce",
      techs: ["#reactjs", "css"],
    },
    {
      index: 8,
      name: "CodeCraft Academy",
      imgsrc: "/projects/online-learning.png",
      descr: "Your one-stop destination to purchase coding tutorials and book transformative coding-related events for an immersive learning experience.", 
      github:"https://github.com/abhishekdasz/e-commerce",
      techs: ["#reactjs", "css"],
    },
    {
      index: 9,
      name: "Nature's Wanderlust",
      imgsrc: "/projects/natures-wanderlust.png",
      descr: "An online platform offering a seamless shopping experience, showcasing products, facilitating secure transactions, and ensuring customer satisfaction.", 
      github:"https://github.com/abhishekdasz/e-commerce",
      techs: ["#html", "css", "javascript"],
    },
    {
      index: 10,
      name: "My Home Garden",
      imgsrc: "/projects/home-garden.png",
      descr: "An online platform offering a seamless shopping experience, showcasing products, facilitating secure transactions, and ensuring customer satisfaction.", 
      github:"https://github.com/abhishekdasz/e-commerce",
      techs: ["#html", "css", "javascript"],
    },
    {
      index: 11,
      name: "Tom and Jerry Game",
      imgsrc: "/projects/tom-n-jerryGame.png",
      descr: "An online platform offering a seamless shopping experience, showcasing products, facilitating secure transactions, and ensuring customer satisfaction.", 
      github:"https://github.com/abhishekdasz/e-commerce",
      techs: ["#html", "css", "javascript"],
    },
    {
      index: 12,
      name: "ProfileBridge",
      imgsrc: "/projects/mern.png",
      descr: "Secure platform to create professional profiles with encrypted passwords, MongoDB storage, and social media integration for portfolio management.", 
      github:"https://github.com/abhishekdasz/mern",
      techs: ["#reactjs", "#nodejs", "#mongodb"],
    },
    {
      index: 13,
      name: "Simple Corona Table",
      imgsrc: "/projects/corona-table.png",
      descr: "An online platform offering a seamless shopping experience, showcasing products, facilitating secure transactions, and ensuring customer satisfaction.", 
      github:"https://github.com/abhishekdasz/e-commerce",
      techs: ["#html", "#inline-css"],
    },
  ]
  
  export {  projects, allprojects };
  